name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v1
      - uses: dimensiondev/github-token-action@latest
        with:
          registry: true
          global: true
      - name: Install `wasm-pack`
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Publish
        run: .github/scripts/publish.sh
