name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      working-directory: ./target-dotnet
      run: dotnet restore
    - name: Build
      working-directory: ./target-dotnet
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./target-dotnet
      run: dotnet test --no-restore --verbosity normal
